# Generated by Django 5.1.3 on 2025-02-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CAJERO', 'Cajero'), ('CLIENTE', 'Cliente'), ('COCINERO', 'Cocinero')], default='CLIENTE', max_length=10),
        ),
    ]
