# Generated by Django 5.1.3 on 2025-02-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ventas_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ventas_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('abierta', models.BooleanField(default=False)),
            ],
        ),
    ]
