# Generated by Django 5.1.3 on 2025-02-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='fecha_apertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='nombre',
            field=models.CharField(default='Caja 1', max_length=50),
        ),
    ]
