# Generated by Django 5.1.3 on 2025-02-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_caja_fecha_apertura_alter_caja_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
