# Generated by Django 5.1.3 on 2025-02-18 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_caja_fecha_cierre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='ventas_efectivo',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='ventas_tarjeta',
        ),
    ]
