# Generated by Django 5.1.3 on 2025-02-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_venta_cantidad_remove_venta_estado_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='customer_name',
            field=models.CharField(default='cliente desconocido', max_length=100),
            preserve_default=False,
        ),
    ]
