# Generated by Django 5.1.3 on 2025-02-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_transaccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
