# Generated by Django 5.1.3 on 2025-02-28 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_remove_transaction_created_at_and_more'),
        ('ventas', '0006_delete_transaccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Venta', 'Venta'), ('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('payment_type', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=15, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_transaction_set', to='caja.caja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
